# Upstream changes from _extends are only recognized when modifications are made to this file in the default branch.
_extends: .github
repository:
  name: terraform-aws-route53-alias
  description: Terraform Module to Define Vanity Host/Domain (e.g. `brand.com`) as an ALIAS record
  homepage: https://cloudposse.com/accelerate
  topics: terraform, terraform-modules, route53



